"""Provisional supported Python API for planning and applying organization."""

from smart_file_organizer.application import (
    OrganizationPlan,
    OrganizationPlanConflictError,
    PlanOrganizationRequest,
    apply_organization,
    plan_organization,
)
from smart_file_organizer.errors import (
    BrokenSourceSymlinkError,
    ConfigError,
    DestinationConflictError,
    DestinationExistsError,
    DestinationParentError,
    InvalidSourceError,
    ManifestWriteError,
    SourceMissingError,
    SourceSelectionError,
    UnsafePathError,
    UnsupportedSourceSymlinkError,
)
from smart_file_organizer.models import (
    ClassificationDecision,
    ClassificationCandidate,
    ClassificationEvidence,
    ClassificationOutcome,
    ClassificationSource,
    ConflictStrategy,
    ExecutionResult,
    FileCategory,
    EvidenceSource,
    EvidenceStrength,
    MatchMechanism,
    MoveExecutionRecord,
    MoveStatus,
    PlannedMove,
    TaxonomyProfileName,
)


__all__ = [
    "BrokenSourceSymlinkError",
    "ClassificationCandidate",
    "ClassificationDecision",
    "ClassificationEvidence",
    "ClassificationOutcome",
    "ClassificationSource",
    "ConfigError",
    "ConflictStrategy",
    "DestinationConflictError",
    "DestinationExistsError",
    "DestinationParentError",
    "ExecutionResult",
    "EvidenceSource",
    "EvidenceStrength",
    "FileCategory",
    "InvalidSourceError",
    "ManifestWriteError",
    "MatchMechanism",
    "MoveExecutionRecord",
    "MoveStatus",
    "OrganizationPlan",
    "OrganizationPlanConflictError",
    "PlanOrganizationRequest",
    "PlannedMove",
    "SourceMissingError",
    "SourceSelectionError",
    "TaxonomyProfileName",
    "UnsafePathError",
    "UnsupportedSourceSymlinkError",
    "apply_organization",
    "plan_organization",
]
